generator:
    optimizer: 'adam' # adam or sgd
    # parameter used in loss function
    lambd: 1 # 0 if not specified
    learning_rate:
        base_lr: 1e-4
        max_lr: 5e-3
        step_size: 2000
        
discriminator:
    optimizer: 'sgd' # adam or sgd
    # no of times discriminator will be trained per run of generator
    k: 4 # 1 if not specified
    learning_rate:
        base_lr: 1e-4
        max_lr: 5e-3
        step_size: 2000

cgan:
    epochs: 500
    ckpt_dir: 'cgan_ckpt'
    batch_size: 64
    buffer_size: 500
    validation_size: 100 # only integer
